# Generated by Django 5.2.6 on 2025-10-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
